name: chats
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  grpc: ^3.2.4
  protobuf: ^3.1.0
  stormberry: ^0.13.1
  jaguar_jwt: ^3.0.0
  crypto: ^3.0.3
  encrypt: ^5.0.3

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^3.0.0
  test: ^1.24.9
